// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Station {
    id: string;
    ctime: string;
    system_id: string;
    done: boolean;
    title: string;
    desc?: string;
}
