// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StationForCreate {
    system_id: string;
    title: string;
    visible?: boolean;
    desc?: string;
}
